# Define a macro for name of objects
OBJS = fmt.o word.o line.o
 
# Define macros for name of compiler
CC = gcc
 
# Define a macro for the CC flags
CFLAGS = -Wall -g -std=c99
 
# A rule for building a object file
fmt: $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@ 
 
fmt.o word.o line.o: %.o:%.c 
	$(CC) $(CFLAGS) -c $< -o $@

